### ISSUE TITLE
Thinks String.prototype.indexOf is Array.prototype.indexOf

### ISSUE THREAD

**Issue by zachleat** [tbusser/jscc#7]
```
var sheets = window.document.styleSheets;
        var defined;
        for( var i = 0; i < sheets.length; i++ ){
            if( sheets[ i ].href && sheets[ i ].href.indexOf( href ) > -1 ){
                defined = true;
            }
        }
```

taken from https://github.com/filamentgroup/loadCSS/blob/master/loadCSS.js

**Comment by tbusser** [comment]
Unfortunately this is not something which can be fixed. I have no way of knowing if `href` is a String or an Array object because all checks are handled with regexs. The only way to try and fix this would be to completely change the way JSCC works and that is a project I don't have time for at this moment. 

I figure it is better to generate a false positive every once in a while than to try and narrow down the regex to prevent this case from happening and in the process missing other instances of `indexOf` which should be flagged.

Anyway, thanks for the bringing it to my attention and sorry I don't have better fix for it.

**Comment by CanRau** [comment]
Just stumbled across the same issue..and after 30secs I realized I'm using indexOf on a string, so nothing to worry understand your point, totally valid!
Maybe you could include a little note so the user makes sure to recheck is usage of indexOf..I'm sure most will know it immediately or find it out fast, but it could save some seconds haha ;)

If not..don't worry..just a little thought of mine..
And by the way thanks for this nice little helper! Good work!
